// SPDX-License-Identifier: AGPL-3.0-or-later

package proxyconfig_test

import (
	"fmt"
	"os"
	"strings"
	"testing/fstest"

	"github.com/airencracken/comfylib/proxyconfig"
)

func ExampleRun() {
	// An app passes its embedded examples; a MapFS stands in here.
	spec := proxyconfig.Spec{
		App:              "witmoot",
		ExampleDomain:    "board.example.org",
		DefaultUpstream:  "127.0.0.1:8082",
		ProxyEnvironment: "WITMOOT_TRUSTED_PROXIES=127.0.0.1/32,::1/128",
		Examples: fstest.MapFS{
			"caddy/Caddyfile": {Data: []byte("board.example.org {\n\treverse_proxy 127.0.0.1:8082\n}\n")},
		},
	}
	var out strings.Builder
	if err := proxyconfig.Run(spec, []string{"caddy", "--domain", "forum.example.net"}, &out); err != nil {
		fmt.Fprintln(os.Stderr, err)
		return
	}
	fmt.Print(out.String())
	// Output:
	// # Generated by witmoot proxy-config caddy.
	// # Set these in /etc/conf.d/witmoot (OpenRC) or /etc/witmoot/witmoot.env (systemd):
	// # WITMOOT_ADDR=127.0.0.1:8082
	// # WITMOOT_BASE_URL=https://forum.example.net
	// # WITMOOT_SECURE_COOKIES=true
	// # WITMOOT_TRUSTED_PROXIES=127.0.0.1/32,::1/128
	// # Validate the complete proxy configuration before reloading.
	//
	// forum.example.net {
	// 	reverse_proxy 127.0.0.1:8082
	// }
}
