// SPDX-License-Identifier: AGPL-3.0-or-later

package proxyconfig

import (
	"bytes"
	"errors"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
	"testing/fstest"
)

const (
	exampleDomain    = "app.example.org"
	defaultUpstream  = "127.0.0.1:8082"
	proxyEnvironment = "EXAMPLEAPP_TRUSTED_PROXIES=127.0.0.1/32,::1/128"
)

// testSpec uses witmoot's examples, renamed to exampleapp.
func testSpec() Spec {
	return Spec{
		App:              "exampleapp",
		ExampleDomain:    exampleDomain,
		DefaultUpstream:  defaultUpstream,
		ProxyEnvironment: proxyEnvironment,
		Examples:         os.DirFS("testdata"),
	}
}

func TestProxyConfigurations(t *testing.T) {
	for _, server := range []string{"caddy", "nginx", "apache"} {
		t.Run(server, func(t *testing.T) {
			config, err := Render(testSpec(), Options{Server: server, Domain: "photos.example.net", Upstream: "[::1]:9100"})
			if err != nil {
				t.Fatal(err)
			}
			for _, want := range []string{
				"photos.example.net", "[::1]:9100", proxyEnvironment,
				"# Generated by exampleapp proxy-config " + server + ".",
				"/etc/conf.d/exampleapp (OpenRC) or /etc/exampleapp/exampleapp.env (systemd)",
				"# EXAMPLEAPP_ADDR=[::1]:9100", "# EXAMPLEAPP_BASE_URL=https://photos.example.net", "# EXAMPLEAPP_SECURE_COOKIES=true",
			} {
				if !strings.Contains(config, want) {
					t.Errorf("missing %q in generated %s config", want, server)
				}
			}
			if strings.Contains(config, exampleDomain) || strings.Contains(config, defaultUpstream) {
				t.Fatal("generated config contains the original example's host or upstream")
			}
			if server != "caddy" {
				if !strings.Contains(config, `"/etc/letsencrypt/live/photos.example.net/fullchain.pem"`) {
					t.Fatal("default certificate path does not follow the domain")
				}
				custom, err := Render(testSpec(), Options{Server: server, Domain: "photos.example.net", Certificate: "/custom certs/fullchain.pem", Key: "/custom certs/key.pem"})
				if err != nil || !strings.Contains(custom, `"/custom certs/fullchain.pem"`) || !strings.Contains(custom, `"/custom certs/key.pem"`) {
					t.Fatalf("custom TLS paths were not quoted: %v\n%s", err, custom)
				}
			}
		})
	}
}

func TestSpecControlsNamesAndPaths(t *testing.T) {
	spec := testSpec()
	spec.EnvPrefix = "EX"
	spec.Examples = fstest.MapFS{
		"sites/caddy.txt": {Data: []byte("app.example.org {\n\treverse_proxy 127.0.0.1:8082\n}\n")},
	}
	spec.Paths = map[string]string{"caddy": "sites/caddy.txt"}
	config, err := Render(spec, Options{Server: "caddy", Domain: "x.example.net"})
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(config, "# EX_ADDR=127.0.0.1:8082") || !strings.Contains(config, "x.example.net {") {
		t.Fatalf("spec names or paths ignored:\n%s", config)
	}
	// With explicit paths, servers left out are unsupported.
	if _, err := Render(spec, Options{Server: "nginx", Domain: "x.example.net"}); err == nil {
		t.Fatal("rendered a server the spec does not provide")
	}
	// A missing example is an error, not empty output.
	spec.Paths = map[string]string{"caddy": "missing"}
	if out, err := Render(spec, Options{Server: "caddy", Domain: "x.example.net"}); err == nil || out != "" {
		t.Fatalf("missing example: %q, %v", out, err)
	}
}

func TestInvalidSpecsAreRefused(t *testing.T) {
	for name, change := range map[string]func(*Spec){
		"no app":             func(s *Spec) { s.App = "" },
		"app with slash":     func(s *Spec) { s.App = "../etc" },
		"app with newline":   func(s *Spec) { s.App = "app\nx" },
		"bad prefix":         func(s *Spec) { s.EnvPrefix = "A B" },
		"bad example domain": func(s *Spec) { s.ExampleDomain = "" },
		"public upstream":    func(s *Spec) { s.DefaultUpstream = "0.0.0.0:80" },
		"multiline env":      func(s *Spec) { s.ProxyEnvironment = "A=1\nlisten 80;" },
		"no examples":        func(s *Spec) { s.Examples = nil },
	} {
		spec := testSpec()
		change(&spec)
		if out, err := Render(spec, Options{Server: "caddy", Domain: "x.example.net"}); err == nil || out != "" {
			t.Errorf("%s: rendered %q", name, out)
		}
		var buf bytes.Buffer
		if err := Run(spec, []string{"caddy", "--domain", "x.example.net"}, &buf); err == nil || buf.Len() != 0 {
			t.Errorf("%s: Run accepted the spec", name)
		}
	}
}

func TestProxyConfigRejectsInjectionAndInvalidAddresses(t *testing.T) {
	base := Options{Server: "nginx", Domain: "photos.example.net", Upstream: defaultUpstream}
	var cases []Options
	for _, domain := range []string{"", "https://photos.example.net", "bad.example/path", "*.example.net", "photos.example.net:443", "bad\nserver{}", "bad;include", "bad$host", "bad..example", "-bad.example", "bad_.example", strings.Repeat("a", 64) + ".example", "bad example", "exämple.net", strings.Repeat("a.", 127) + "aa"} {
		value := base
		value.Domain = domain
		cases = append(cases, value)
	}
	for _, upstream := range []string{":8080", "0.0.0.0:8080", "192.0.2.1:8080", "http://127.0.0.1:8080", "127.0.0.1:0", "127.0.0.1:65536", "localhost:abc", "localhost:8080;", "localhost:8080\n", "localhost:+8080", "[fe80::1%lo]:8080", "[::1%lo]:8080", "127.0.0.1"} {
		value := base
		value.Upstream = upstream
		cases = append(cases, value)
	}
	for _, path := range []string{"relative.pem", "/certs/", "/certs/\ninclude", "/certs/$variable", "/certs/\".pem", "/certs/a;include", "/certs/\\.pem", "/certs/{x}.pem"} {
		value := base
		value.Certificate, value.Key = path, "/certs/key.pem"
		cases = append(cases, value)
	}
	cases = append(cases,
		Options{Server: "unknown", Domain: base.Domain},
		Options{Server: "", Domain: base.Domain},
		Options{Server: "nginx", Domain: base.Domain, Certificate: "/cert.pem"},
		Options{Server: "nginx", Domain: base.Domain, Key: "/key.pem"},
		Options{Server: "caddy", Domain: base.Domain, Certificate: "/cert.pem", Key: "/key.pem"},
	)
	for _, value := range cases {
		if output, err := Render(testSpec(), value); err == nil || output != "" {
			t.Errorf("invalid options accepted: %+v => %q, %v", value, output, err)
		}
	}
}

func TestProxyConfigCLI(t *testing.T) {
	for _, args := range [][]string{{"--help"}, {"-h"}, {"caddy", "--help"}, {"nginx", "--help"}, {"apache", "--help"}} {
		var output bytes.Buffer
		if err := Run(testSpec(), args, &output); err != nil || !strings.Contains(output.String(), "Usage:") {
			t.Fatalf("help %v: %v, %s", args, err, &output)
		}
		if !strings.Contains(output.String(), "exampleapp proxy-config") {
			t.Fatalf("help does not name the app: %s", &output)
		}
	}
	var output bytes.Buffer
	if err := Run(testSpec(), []string{"caddy", "--domain", "photos.example.net"}, &output); err != nil || !strings.Contains(output.String(), "reverse_proxy "+defaultUpstream) {
		t.Fatalf("render: %v, %s", err, &output)
	}
	for _, args := range [][]string{nil, {"unknown"}, {"caddy"}, {"caddy", "--domain", "photos.example.net", "extra"}, {"caddy", "--bogus"}} {
		output.Reset()
		err := Run(testSpec(), args, &output)
		if err == nil || strings.Contains(output.String(), "reverse_proxy") {
			t.Fatalf("bad arguments emitted config: %v => %v, %s", args, err, &output)
		}
	}
	sentinel := errors.New("output closed")
	if err := Run(testSpec(), []string{"caddy", "--domain", "photos.example.net"}, brokenWriter{sentinel}); !errors.Is(err, sentinel) {
		t.Fatalf("output error = %v", err)
	}
	if err := Run(testSpec(), []string{"--help"}, brokenWriter{sentinel}); !errors.Is(err, sentinel) {
		t.Fatalf("help output error = %v", err)
	}
}

type brokenWriter struct{ err error }

func (w brokenWriter) Write([]byte) (int, error) { return 0, w.err }

func TestGeneratedCaddyConfigurationAdapts(t *testing.T) {
	binary := os.Getenv("CADDY_BINARY")
	if binary == "" {
		var err error
		binary, err = exec.LookPath("caddy")
		if err != nil {
			t.Skip("install Caddy to validate its generated configuration")
		}
	}
	config, err := Render(testSpec(), Options{Server: "caddy", Domain: "photos.example.net", Upstream: "[::1]:9100"})
	if err != nil {
		t.Fatal(err)
	}
	path := filepath.Join(t.TempDir(), "Caddyfile")
	if err := os.WriteFile(path, []byte(config), 0o600); err != nil {
		t.Fatal(err)
	}
	if output, err := exec.Command(binary, "adapt", "--adapter", "caddyfile", "--config", path).CombinedOutput(); err != nil {
		t.Fatalf("Caddy rejected generated configuration: %v\n%s", err, output)
	}
}

// Whatever a person types, the output either fails or contains none of the
// characters that could end a directive in any of the three servers.
func FuzzRender(f *testing.F) {
	f.Add("nginx", "photos.example.net", "127.0.0.1:9000", "/c/cert.pem", "/c/key.pem")
	f.Add("apache", "a;b", "[::1]:1", "", "")
	f.Add("caddy", "x.example", "localhost:80", "", "")
	f.Fuzz(func(t *testing.T, server, domain, upstream, cert, key string) {
		config, err := Render(testSpec(), Options{Server: server, Domain: domain, Upstream: upstream, Certificate: cert, Key: key})
		if err != nil {
			return
		}
		for _, value := range []string{domain, upstream, cert, key} {
			if strings.ContainsAny(value, ";{}$\"\\\n\r#<>'`") {
				t.Fatalf("accepted %q into %s config", value, server)
			}
		}
		if !strings.Contains(config, domain) {
			t.Fatal("domain missing from output")
		}
	})
}
